<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @authorSkeleton     Ralf Eggert <ralf@travello.de>  * @author	   		   Mirco Klink  * @author	   		   Mirco Klink
 * @linkSkeleton       https://github.com/zf3buch/zendframework-center
 * @link 			 https://github.com/MiKliWeb87/Zend3_Projekt2  * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

use TravelCenterBackend\Form\TravelCenterFormInterface;

/** @var TravelCenterFormInterface $form */
$form = $this->travelcenterForm;

$listLink = $this->url('travelcenter-backend', [], true);

$this->headTitle('travelcenter_backend_title_display_add');
$this->h1('travelcenter_backend_h1_display_add');
?>
<p>
  <a href="<?= $listLink ?>" class="btn btn-default">
    <i class="fa fa-list"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('travelcenter_backend_action_overview') ?>
    </span>
  </a>
</p>
<div class="well">
  <?= $this->bootstrapForm($form); ?>
</div>
