<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @authorSkeleton     Ralf Eggert <ralf@travello.de>  * @author 	 	 	   Mirco Klink
 * @linkSkeleton       https://github.com/zf3buch/zendframework-center
 * @link 			   https://github.com/MiKliWeb87/Zend3_Projekt2  * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

use HolidaycenterBackend\Form\HolidaycenterFormInterface;

/** @var HolidaycenterFormInterface $form */
$form = $this->holidaycenterForm;

$listLink = $this->url('holidaycenter-backend', [], true);

$this->headTitle('holidaycenter_backend_title_display_add');
$this->h1('holidaycenter_backend_h1_display_add');
?>
<p>
  <a href="<?= $listLink ?>" class="btn btn-default">
    <i class="fa fa-list"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('holidaycenter_backend_action_overview') ?>
    </span>
  </a>
</p>
<div class="well">
  <?= $this->bootstrapForm($form); ?>
</div>
