<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @authorSkeleton     Ralf Eggert <ralf@travello.de>  * @author 	 	 	   Mirco Klink
 * @linkSkeleton       https://github.com/zf3buch/zendframework-center
 * @link 			   https://github.com/MiKliWeb87/Zend3_Projekt2  * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

use AdvertModel\Entity\AdvertEntity;

/*Detailanzeige der Annoncen für den normalen User */

/** @var AdvertEntity $advert */
$advert = $this->advert;

if ($advert->getType() == 'holiday') 
{
  $color         = 'primary';
  $advertMessage = 'advert_frontend_message_type_holiday';
  $listLink      = $this->url('advert-holiday', [], true);
  $listText      = 'advert_frontend_action_back_holidays';
} else 
{
  $color         = 'success';
  $advertMessage = 'advert_frontend_message_type_shortholiday';
  $listLink      = $this->url('advert-shortholiday', [], true);
  $listText      = 'advert_frontend_action_back_shortholidays';
}

$this->headTitle($advert->getTitle());
$this->h1($advert->getTitle());
?>
<p class="text-center">
  <a class="btn btn-default" href="<?= $listLink; ?>">
    <i class="fa fa-arrow-circle-left"></i>
    <?= $this->translate($listText); ?>
  </a>
</p>
<div class="panel panel-<?= $color ?>">
  <div class="panel-heading clearfix">
    <div class="left-text">
      <strong><?= $advert->getTitle(); ?></strong>
    </div>
    <div class="right-text">
      <?= $advert->getHolidaycenter()->getName() ?>
    </div>
  </div>
  <div class="panel-body">
    <div class="col-sm-9">
      <p><?= $advert->getText(); ?></p>
	  
	<?php if($advert->getImage() != null): //NEU Wenn Bild da?>
	  <img src="<?= $advert->getImage() //NEU ?>" style="width:300px; height:200px;"> 
		<div class="col-sm-9 form-control-static">  
			<a target="_blank" href="<?= $advert->getImage() ?>" 
			class="btn btn-default" role="button" style="float:left;">
			<?= $this->translate('advert_frontend_label_button')?></a><!--NEU -->
		</div>
	<?php else: //Kein Bild vorhanden?> 
		<p id="noImage"> <?= $this->translate('advert_frontend_message_no_image');?> </p>
		<?php endif; ?>	
    </div>
	
    <div class="col-sm-3 holidaycenter">
      <p>
        <img class="img-responsive"
             src="<?= $advert->getHolidaycenter()->getLogo() ?>">
      </p>
      <h5>
        <strong>
          <?= $this->translate('advert_frontend_label_type_contact'); ?>
        </strong>
      </h5>
      <p><?= $advert->getHolidaycenter()->getContact() ?></p>
      <p><?= $advert->getHolidaycenter()->getEmail() ?></p>
    </div>
  </div>
  <div class="panel-footer clearfix">
    <div class="left-text">
      <div class="label label-<?= $color; ?>">
        <?= sprintf(
            $this->translate($advertMessage), $advert->getLocation()
        ); ?>
      </div>
    </div>
    <div class="right-text">
      <div class="label label-<?= $color; ?>">
        <?= sprintf(
            $this->translate('advert_frontend_label_last_update'),
            $this->dateFormat(
                $advert->getUpdated(),
                IntlDateFormatter::MEDIUM,
                IntlDateFormatter::MEDIUM
            )
        ); ?>
      </div>
    </div>
  </div>
</div>
<p class="text-center">
  <a class="btn btn-default" href="<?= $listLink; ?>">
    <i class="fa fa-arrow-circle-left"></i>
    <?= $this->translate($listText); ?>
  </a>
</p>
