<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @authorSkeleton     Ralf Eggert <ralf@travello.de>  * @author	   		   Mirco Klink  * @author	   		   Mirco Klink
 * @linkSkeleton       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

$this->headTitle('user_frontend_title_register_index');
$this->h1('user_frontend_h1_register_index');
?>
<div class="panel panel-success">
  <div class="panel-heading">
    <?= $this->translate('user_frontend_h2_register') ?>
  </div>
  <div class="panel-body">
    <?= $this->userShowRegisterForm(); ?>
  </div>
</div>
