<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @authorSkeleton     Ralf Eggert <ralf@travello.de>  * @author	   		   Mirco Klink  * @author	   		   Mirco Klink
 * @linkSkeleton       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

$this->headTitle('advert_frontend_title_modify_add');
$this->h1('advert_frontend_h1_modify_add');
?>
<div class="well">
  In Kürze mehr...
</div>
