<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @authorSkeleton     Ralf Eggert <ralf@travello.de>  * @author 	 	 	   Mirco Klink
 * @linkSkeleton       https://github.com/zf3buch/zendframework-center
 * @link 			   https://github.com/MiKliWeb87/Zend3_Projekt2  * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

use AdvertModel\Entity\AdvertEntity;

/** @var AdvertEntity $holiday */
$holiday     = $this->randomHoliday;

/** @var AdvertEntity $shortholiday */
$shortholiday = $this->randomShortholiday;

$holidayText = strip_tags($holiday->getText());
$holidayText = implode(
    ' ', array_slice(explode(' ', $holidayText), 0, 50)
);

$shortholidayText = strip_tags($shortholiday->getText());
$shortholidayText = implode(
    ' ', array_slice(explode(' ', $shortholidayText), 0, 50)
);

$holidayDetailLink = $this->url('advert-holiday/detail', ['id' => $holiday->getId()], true);

$shortholidayDetailLink = $this->url(
    'advert-shortholiday/detail', ['id' => $shortholiday->getId()], true
);

$holidayListLink = $this->url('advert-holiday', [], true);

$shortholidayListLink = $this->url('advert-shortholiday', [], true);

$this->h1('application_h1_index_index');
?>

<div class="row">
  <div class="col-sm-6">
    <h2>
      <a href="<?= $holidayListLink; ?>">
        <?= $this->translate('application_h2_holidays') ?>
      </a>
    </h2>

    <div class="panel panel-primary">
      <div class="panel-heading clearfix">
        <strong>
          <a href="<?= $holidayDetailLink; ?>"><?= $holiday->getTitle(); ?></a>
        </strong>
      </div>
      <div class="panel-body">
        <p>
          <img src="<?= $holiday->getHolidaycenter()->getLogo() ?>"
               class="img-responsive center-block">
        </p>
        <p><?= $holidayText; ?> ...</p>
        <p class="text-center">
          <a href="<?= $holidayDetailLink ?>" class="btn btn-primary">
            <?= $this->translate('advert_frontend_action_show_holiday'); ?>
          </a>
        </p>
      </div>
      <div class="panel-footer clearfix">
        <div class="left-text">
          <div class="label label-primary">
            <?= sprintf(
                $this->translate('advert_frontend_message_type_holiday'),
                $holiday->getLocation()
            ); ?>
          </div>
        </div>
        <div class="right-text">
          <div class="label label-primary">
            <?= sprintf(
                $this->translate('advert_frontend_label_last_update'),
                $shortholiday->getUpdated()->format('d.m.Y H:i:s')
            ); ?>
          </div>
        </div>
      </div>
    </div>
    <p class="text-center">
      <a href="<?= $holidayListLink; ?>" class="btn btn-primary">
        <?= $this->translate('advert_frontend_action_all_holidays') ?>
      </a>
    </p>
  </div>
  <div class="col-sm-6">
    <h2>
      <a href="<?= $shortholidayListLink; ?>">
        <?= $this->translate('application_h2_shortholidays') ?>
      </a>
    </h2>

    <div class="panel panel-success">
      <div class="panel-heading clearfix">
        <strong>
          <a href="<?= $shortholidayDetailLink; ?>">
            <?= $shortholiday->getTitle(); ?>
          </a>
        </strong>
      </div>
      <div class="panel-body">
        <p>
          <img src="<?= $shortholiday->getHolidaycenter()->getLogo() ?>"
               class="img-responsive center-block">
        </p>
        <p><?= $shortholidayText; ?> ...</p>
        <p class="text-center">
          <a href="<?= $shortholidayDetailLink ?>" class="btn btn-success">
            <?= $this->translate('advert_frontend_action_show_shortholiday'); ?>
          </a>
        </p>
      </div>
      <div class="panel-footer clearfix">
        <div class="left-text">
          <div class="label label-success">
            <?= sprintf(
                $this->translate('advert_frontend_message_type_shortholiday'),
                $shortholiday->getLocation()
            ); ?>
          </div>
        </div>
        <div class="right-text">
          <div class="label label-success">
            <?= sprintf(
                $this->translate('advert_frontend_label_last_update'),
                $shortholiday->getUpdated()->format('d.m.Y H:i:s')
            ); ?>
          </div>
        </div>
      </div>
    </div>
    <p class="text-center">
      <a href="<?= $shortholidayListLink; ?>" class="btn btn-success">
        <?= $this->translate('advert_frontend_action_all_shortholidays') ?>
      </a>
    </p>
  </div>
</div>
